apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 821e552b-00ef-4f0a-9b84-51b404a20048
    run.googleapis.com/build-image-uri: asia-northeast2-docker.pkg.dev/gen-lang-client-0971910955/cloud-run-source-deploy/gemdi
    run.googleapis.com/build-name: projects/933398348693/locations/asia-northeast2/builds/821e552b-00ef-4f0a-9b84-51b404a20048
    run.googleapis.com/build-source-location: gs://run-sources-gen-lang-client-0971910955-asia-northeast2/services/gemdi/1770493370.136274-f9b9725c15714460983fa86a1fd69aee.zip#1770493372350103
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 555.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/operation-id: e053ebdc-7fce-4cc2-ac45-be9e61887831
    run.googleapis.com/urls: '["https://gemdi-933398348693.asia-northeast2.run.app","https://gemdi-bci6otsgoa-dt.a.run.app"]'
    serving.knative.dev/creator: swanzayar07@gmail.com
    serving.knative.dev/lastModifier: 933398348693-compute@developer.gserviceaccount.com
  creationTimestamp: '2026-02-07T19:44:13.889982Z'
  generation: 5
  labels:
    cloud.googleapis.com/location: asia-northeast2
    commit-sha: b997c9fedafb1b2886fb8f2440e25df1df290942
    gcb-build-id: 7d03f57e-a8dd-41e6-b737-725883427af3
    gcb-trigger-id: e658285c-dbe6-46aa-b6cd-41c0d399b175
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: gemdi
  namespace: '933398348693'
  resourceVersion: AAZKQUJYetk
  selfLink: /apis/serving.knative.dev/v1/namespaces/933398348693/services/gemdi
  uid: 0ea11435-8144-48ed-bd39-119a57eeabdd
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 555.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: wlvxfdglta
        commit-sha: b997c9fedafb1b2886fb8f2440e25df1df290942
        gcb-build-id: 7d03f57e-a8dd-41e6-b737-725883427af3
        gcb-trigger-id: e658285c-dbe6-46aa-b6cd-41c0d399b175
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: asia-northeast2-docker.pkg.dev/gen-lang-client-0971910955/cloud-run-source-deploy/gemdi/gemdi:b997c9fedafb1b2886fb8f2440e25df1df290942
        name: gemdi-1
        ports:
        - containerPort: 3000
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 3000
          timeoutSeconds: 240
      serviceAccountName: 933398348693-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://gemdi-bci6otsgoa-dt.a.run.app
  conditions:
  - lastTransitionTime: '2026-02-07T19:53:26.688473Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-02-07T19:53:21.079417Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-02-07T19:53:26.653489Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: gemdi-00004-9lm
  latestReadyRevisionName: gemdi-00004-9lm
  observedGeneration: 5
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: gemdi-00004-9lm
  url: https://gemdi-bci6otsgoa-dt.a.run.app
